### ISSUE TITLE
Support DANE

### ISSUE THREAD

**Issue by BenBE** [SSLMate/whatsmychaincert#4]
Please support DANE for TLS chain verification.

**Comment by AGWA** [comment]
DANE [is an architectural dead-end in browsers](https://www.imperialviolet.org/2015/01/17/notdane.html).  While it _might_ have a future outside of the browser (e.g. in server-to-server SMTP/XMPP), it seems premature to work on supporting it, especially when whatsmychaincert is mainly focused on the browser use case, and isn't trying to be a general-purpose TLS testing tool.
