### ISSUE TITLE
Cannot install to root tree

### ISSUE THREAD

**Issue by BenBE** [SSLMate/whatsmychaincert#5]
Based on a check in https://github.com/SSLMate/whatsmychaincert/blob/master/Makefile#L31 you can't cleanly install to /

**Comment by AGWA** [comment]
I can't imagine why anyone would want to install to /, but the check you cited doesn't prevent doing so: just use `DESTDIR=/`.

**Comment by BenBE** [comment]
Yes, the check I cited doesn't prevent using DESTDIR=/ to install, but the reason I brought this up was because doing so causes bad path names like //foo to be used.
