### ISSUE TITLE
Continued compliance with the HSTS preload requirements.

### ISSUE THREAD

**Issue by bardiharborow** [SSLMate/whatsmychaincert#6]
Hey! `whatsmychaincert.com` is currently HSTS preloaded, but has not continued to remain compliant with the [preload requirements](https://hstspreload.org/). If you are able to remedy this, it would be highly appreciated. This will ensure that if Chrome begins delisting non-compliant domains that yours will not be affected. Over at [EFForg/https-everywhere](https://github.com/EFForg/https-everywhere), we can't remove rewrite rules for domains that are non-compliant because that would present a security risk if Chrome then also removes them. Your domain is one of hundreds of non-compliant domains which add unnecessary maintenance and file size to our rulesets. Any assistance you can provide is appreciated.

**Comment by AGWA** [comment]
Thanks @bardiharborow.  I think `whatsmychaincert.com` is compliant now, but in any case it was submitted before Chrome 51 and is therefore not subject to the continued requirements. I don't think there would be any risk from removing the HTTPS Everywhere rule for `whatsmychaincert.com` if that's what you want to do.

**Comment by bardiharborow** [comment]
Confirmed fixed! In your case, you are correct that there's less risk, but there are good reasons to maintain best practice anyway. Have a great day. :)
